#!/usr/bin/perl

use 5.024;
use strict;
use warnings;
use utf8;

use English;
use Getopt::Long qw(VersionMessage :config no_ignore_case bundling);
use Markdown::Perl;
use Pod::Usage;

our $VERSION = $Markdown::Perl::VERSION; ## no critic (ProhibitComplexVersion,RequireConstantVersion)

GetOptions(
  "help|h" => sub { pod2usage(-verbose => 1, -exitval => 0); },
  "helpfull|help-full|man" => sub { pod2usage(-verbose => 2, -exitval => 0); },
  "help-options" => sub { pod2usage(-verbose => 2, -exitval => 0, -input => $INC{'Markdown/Perl/Options.pm'}); },
  "version|v" => sub { VersionMessage(-exitval => 0) },
) or pod2usage(-verbose => 0, -exitval => 2);

my $input;
{
  local $INPUT_RECORD_SEPARATOR = undef;
  $input = <>;
}

print Markdown::Perl::convert($input);

__DATA__

=pod

=encoding utf8

=head1 NAME

pmarkdown – Very configurable Markdown processor written in pure Perl

=head1 SYNOPSIS

  pmarkdown < file_in.md > file_out.html_fragment

=head1 DESCRIPTION

B<pmarkdown>

=head1 OPTIONS

=over 8

=item B<--help>

Show a short help message about the program.

=item B<--helpfull>

Show the complete man page of the program.

=back

=head1 AUTHOR

This program has been written by L<Mathias Kende|mailto:mathias@cpan.org>.

=head1 LICENCE

Copyright 2024 Mathias Kende

This program is distributed under the MIT (X11) License:
L<http://www.opensource.org/licenses/mit-license.php>

Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

=head1 SEE ALSO

L<cmark(1)>,
L<CommonMark Spec|https://spec.commonmark.org/0.30/#links>

=cut
